initial_bladelets_number: 0
initial_bladelets_number_by_light: 0
initial_bladelets_number_by_temperature: 0
initial_bladelet_length: 20
initial_age: 0
initial_day_age: 0
initial_population: 4
max_age: 1875
most_appropriate_temperature_n: 18
under_limit_temperature_n: 10
upper_limit_temperature_n: 22
most_appropriate_temperature_l: 15.5
under_limit_temperature_l: 10
upper_limit_temperature_l: 16
max_photosynthesis_rate: 65
threshold_photosynthesis_rate_ratio: 0.41215
bladelets_number_increase_const_by_light: 1.3
bladelets_number_decrease_const_by_light: 9.75
bladelets_number_increase_const_by_temperature: 0.05
bladelets_number_decrease_const_by_temperature: 0.185
bladelet_length_increase_const: 0.365
bladelet_length_decrease_const: 0.425
bladelet_aspect_ratio: 0.1
surface_density: 0.8
breedable_day_age: 365
breedable_month: 1
reproductive_rate: 1